{
 "title": "Op App - Custom Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Op App - App Config Value Tracker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_test_config_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Op App - Request Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Op App - Status Code Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "app_status_code_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Op App - Go Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}