services:

  op-prometheus:
    image: prom/prometheus:v2.45.3
    container_name: op-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  op-node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: op-node-exporter
    restart: unless-stopped
    expose:
      - 9100

  op-grafana:
    image: grafana/grafana:10.2.4
    container_name: op-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards/
