services:

  op-app:
    image: op-app:latest
    build:
      context: ../src/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8181
    expose:
      - 8181
    # ports:
    #   - "8181-8199:8181"
    deploy:
      replicas: 3

  op-proxy:
    image: nginx:alpine
    container_name: op-proxy
    hostname: 'nginx'
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - op-app
