global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
    
scrape_configs:
- job_name: 'prometheus'
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - op-prometheus:9090

- job_name: 'node'
  static_configs:
    - targets:
      - op-node-exporter:9100

- job_name: 'op-dev-container'
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - op-dev-container:8181

- job_name: 'op-app'
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      filters:
        - name: "label"
          values:
            - "com.docker.compose.service=op-app"
  relabel_configs:
    - source_labels: [__meta_docker_container_port_public]
      action: replace
      target_label: __address__
      regex: "([0-9]+)"
      replacement: "$1"